### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by hoijui** [quotient-im/Quaternion#691] opened 2020-08-08 06:02 UTC
### Description

I can not register an account through Quaternion.
I would like to be able to do that.

### Elaboration (optional to read)

Probably a common scenario (as it happened to us):
We setup a synapse server.
On the stock greetings page, it says something like:

```markdown
It works! Please get a client from [here](link-to-list-of-clients)
```

and that's about it.
Thus, this information clearly assumes, that one is able to create an account with any of these clients.
If I choose a client that does not allow it, I am stuck....
"What did I do wrong? I can;t create the account on the servers page nor in the client... Matrix is stupid!"
not good! This sieves out a lot of people from the get go, or at least leaves behind a bad taste about this matrix stuff.

### Version information

- **Quaternion version**: 0.0.9.4e
- **Install method**: `apt-get`
- **Platform**: Debian testing

**Comment by KitsuneRal** [comment] 2020-08-08 06:31
It's a duplicate of the oldest still open issue, #29.

**Closed by KitsuneRal** 2020-08-08 06:31 UTC
Labels: duplicate
