### ISSUE TITLE
Room description window constantly oscillates between one line and two lines.

### ISSUE THREAD

**Issue by dreirund** [quotient-im/Quaternion#916] opened 2024-11-11 18:07 UTC
I just compiled Quaternion from this git repository using [this modified recipe](https://aur.archlinux.org/packages/quaternion-git#comment-998090), and I opened a room that has a description and the description window constantly oscillates between two lines, one line window height and scrollbars and one line, two lines window height and no scrollbars.

I attach a video recording this (the overlayed windows are there to censor sensitive information).

[description_oscillating.webm](https://github.com/user-attachments/assets/35f2180a-eb0d-48af-a2f3-e6f6db36ab4e)

**Comment by KitsuneRal** [comment] 2024-11-11 19:15
There's an inherent problem with text layout if scrollbars are allowed to disappear when they are not needed; but showing them at all times is not the best option in this case either. I could say it's a problem in QML but I think I don't make it easier with my dynamic height adjustments. I'll see if it can be helped.

**Comment by KitsuneRal** [comment] 2024-11-11 19:26
Btw, I took a look at the recipe, and I have a couple of comments on it:
- It's more accurate to build the version `0.0.97~beta.git*` if that's allowed by your distribution rules; although, admittedly, the difference from 0.0.96.1 is so far minimal
- `-DBUILD_WITH_QT6` is no more supported because it's always Qt 6 now; you can safely drop it
- `-DBUILD_TESTING=OFF` works on libQuotient but not on Quaternion; as I understand it, you build Quaternion with an out-of-tree libQuotient (which is usually recommended for distro packages), and that case, this option has no effect

**Comment by KitsuneRal** [comment] 2024-11-11 19:33
Can you check if [this branch](https://github.com/quotient-im/Quaternion/tree/kitsune/fix-room-header-layout-havoc) fixes the problem?

**Comment by dreirund** [comment] 2024-11-11 21:23
> Can you check if [this branch](https://github.com/quotient-im/Quaternion/tree/kitsune/fix-room-header-layout-havoc) fixes the problem?

No, it still oscillates.

(To double check for you if I used the correct source: `git log` after checkout shows as last message

-- %< --

commit bead28bcab7e5f2d488af838bf38cf540b53550d (HEAD -> makepkg, origin/kitsune/fix-room-header-layout-havoc)
Author: Kitsune Ral <censored>
Date:   Mon Nov 11 20:32:12 2024 +0100

    Timeline: Don't mess with room header padding
    
    Recalculation of padding depending on whether the scroll bar is there
    can easily break the already fragile layout logic, bringing minimal
    benefits in return (it was made to avoid the text ending up under
    transient scrollbars that are overlapping with the client area - but
    transient scrollbars disappear after scrolling anyway).
    
    Hopefully fixes #916.

-- >% --
)

**Comment by KitsuneRal** [comment] 2024-11-12 07:12
Yes, this is the correct commit. Then I'm afraid I have to ask you to change the window or left dock pane size a bit, as a workaround. This may also be a problem with a specific Qt theme, or, as I said, an inherent glitch of the code in Qt that lays out text in a text area. I might try to take it to Qt issue tracker but that's almost never a fast track.

**Comment by KitsuneRal** [comment] 2024-11-16 12:59
@dreirund you may try to check the same branch again (commit https://github.com/quotient-im/Quaternion/commit/62ae4e4ea3803c8f672078662a3b5e36eb4432a4), I'm now sizing the text area closer to Qt's own practices.

**Comment by dreirund** [comment] 2024-11-21 15:54
> *@dreirund you may try to check the same branch again (commit [62ae4e4](https://github.com/quotient-im/Quaternion/commit/62ae4e4ea3803c8f672078662a3b5e36eb4432a4))*

Seems to work now (for the room where I had this issue).

I don't see any scrollbars now, and the area stays constant size (one line in this case).

**Comment by dreirund** [comment] 2024-11-21 15:55
Off-Topic: Any way how I can _verify_ the quaternion session?

**Comment by KitsuneRal** [comment] 2024-12-31 18:05
> > _@dreirund you may try to check the same branch again (commit [62ae4e4](https://github.com/quotient-im/Quaternion/commit/62ae4e4ea3803c8f672078662a3b5e36eb4432a4))_
> 
> Seems to work now (for the room where I had this issue).
> 
> I don't see any scrollbars now, and the area stays constant size (one line in this case).

Thanks for checking, and sorry for the long time to get back. I tried an alternative, simpler, fix on `dev` branch now - I can't reproduce the issue with it where I could before, hopefully it works for you too.

> Off-Topic: Any way how I can _verify_ the quaternion session?

No; it's in the works for now, the next beta is blocked on this feature.

**Comment by KitsuneRal** [comment] 2024-12-31 18:06
Hopefully closed by https://github.com/quotient-im/Quaternion/commit/7c14525c6994c19cefc14979579dc8d330f59d73 ; please reopen if the fix doesn't work for you.

**Closed as completed by KitsuneRal** 2024-12-31 18:06 UTC
Labels: bug/fix
