### ISSUE TITLE
Message highlights can break if another user has the same short display name (can happen with IRC bridges)

### ISSUE THREAD

**Issue by AdamWill** [quotient-im/Quaternion#718] opened 2020-11-25 02:03 UTC
### Description

I started using Matrix and Quaternion recently, so I may be missing something, but it seems like it does very little to alert me when I'm mentioned. My display name being in an unread message doesn't seem to cause the channel name to show in a different color or the message itself to be highlighted in any way, as is typical in IRC clients.

It could be that this is set to work only if my *Matrix id* is mentioned, but it's hard to tell because of the lack of GUI settings. I don't see any discussion of mention configuration in the README file. Anyhow, what I'd like/expect is for there to be support for displaying channels where I've been mentioned in an unread message in a highlight color, displaying messages that include my nick in a highlight color, and configuration options for which string(s) should trigger this behaviour (so I can have it trigger on any variation of my Matrix ID or display name).

### Steps to reproduce

- Log in
- Wait for someone to mention you in a room that isn't the current one
- Be sad that nothing makes it clear that something more urgent than "someone said something somewhere else" happened

### Version information

- **Quaternion version**: quaternion-0.0.9.5-0.2.fc34.x86_64 (Fedora Rawhide)
- **Qt version**: 5.15.1-7.fc34.x86_64
- **Install method**: Fedora package
- **Platform**: Fedora Rawhide

**Comment by KitsuneRal** [comment] 2020-11-25 14:01
Quaternion's capability to detect highlight words is, indeed, fairly limited; however, mentioning your display name should normally cause the highlight. Unfortunately the logic around detecting the display name is somewhat flimsy and may easily unravel if you have, e.g., some non-whitespace, non-alphanumeric characters in it. Is it the case?

**Comment by KitsuneRal** [comment] 2020-11-25 15:02
(Marking it as a mix of bug and enhancement since there's a bit of both in this topic. Also, for the record, this is about making `QuaternionRoom::checkForHighlights()` better; in particular, getting rid of the FIXME in it.)

**Comment by AdamWill** [comment] 2020-11-25 16:36
No, that's not it. I can't reproduce the room name highlight at will, but looking at text highlighting - my display name is 'adamw', and here's how text with ' adamw ' in it shows:


![Screenshot from 2020-11-25 08-35-03](https://user-images.githubusercontent.com/916551/100256068-28bad780-2ef9-11eb-9722-9cf76a14af27.png)

the mention is just underlined blue like a mention of anyone else, and the message as a whole is not highlighted in any way. Is this how it's supposed to be?

**Comment by AdamWill** [comment] 2020-11-25 16:39
BTW, one potentially common case that did occur to me - across IRC bridges you typically show as `displayname[m]`, right? So the mention detection should at least treat any occurrence of that as a mention, I guess. If it doesn't already. But that doesn't seem to be what I ran into here.

**Comment by KitsuneRal** [comment] 2020-11-26 12:33
`displayname[m]` is the actual name usually picked by the bridge. `[]` are non-alphanum characters so that's exactly the case where the highlighting logic unravels. And you're right, it's not what you've run into. This as a pure bug: apparently the highlighting logic got fundamentally broken, possibly after introducing the new HTML filter in Quaternion.

**Comment by KitsuneRal** [comment] 2020-11-26 12:43
Yes, `displayname[m]` is usually picked by the IRC bridge, pretty common across Matrix; and yes, that's exactly a case where the highlighting logic unravels. And you're right, it's not what you've run into. Judging by the screenshot, the highlighting logic got fundamentally broken recenty, possibly after introducing the new HTML filter in Quaternion. Thanks for reporting.

**Comment by AdamWill** [comment] 2020-11-26 16:34
Well, it could also be some kind of toolkit/Wayland issue; as I mentioned I'm running on Fedora Rawhide, which means recent qt5 builds and also running natively on Wayland, which is pretty new. You might want to check it reproduces in other environments too, I guess. For reference, the package is a build of 0.0.9.5-beta2.

**Comment by KitsuneRal** [comment] 2020-11-26 17:33
Quaternion should run fine on a wide range of Qt, from 5.9 all the way through to 5.15 (I'm using 5.12 and 5.15 for development). And yes, you mentioned in the description that it's 0.0.9.5-beta2 (thanks), so basically the most recent pre-release we have atm. And so far I struggle to reproduce it here on RHEL 8.3 (X or Wayland), using the beta2 commit :-\ I have mentions highlighted by orange background.

Am I getting it right that you don't even see a highlight in the room list if you're mentioned in a channel/room you're not looking at?

**Comment by AdamWill** [comment] 2020-11-26 19:01
That part is harder to reproduce at will, but yeah, that's how it seems to be.

If I get a minute I'll try testing some other environments too...

**Comment by AdamWill** [comment] 2020-11-26 21:48
Huh, this is weird - just looked at my quaternion window and saw that now it *is* highlighting mentions of me within a channel, they have a clear yellow backdrop. And now I switched to the fedora-iot channel again and I see them there too.

Since I filed the bug, I think something happened to the Freenode IRC bridge or something and I got dropped and reconnected, because I lost nickserv identification (I noticed that because I got kicked out of several channels that require auth). I restarted Quaternion while I was figuring that out. That's all that's happened that I guess might have changed this. Is anything about highlighting figured out on startup or IRC bridge connect or something and not then recalculated afterwards?

**Comment by KitsuneRal** [comment] 2020-11-30 22:04
It does sound like the IRC bridge might be complicit in that, though I struggle to understand how exactly. It just occurred to me that you might have seen no highlights because your display name somehow got cleared up but then successfully restored. Anyway, it's good that it's working now, and the respective code in Quaternion still have a fundamental FIXME that should be dealt with, so the code will change.

**Comment by AdamWill** [comment] 2020-11-30 23:44
I'm definitely not getting channel name highlights, and that's an issue. I just now noticed someone pinged me for something four hours ago. There was no special highlight for the channel name.

**Comment by KitsuneRal** [comment] 2020-12-01 09:06
How does the name look like, just in case?

**Comment by AdamWill** [comment] 2020-12-01 16:19
The channel name is just in bold, like any channel with unread messages, not different from another channel with unread messages at all.

**Comment by AdamWill** [comment] 2020-12-01 16:50
Aha! So, I figured it out.

There's two issues. I wasn't getting room highlights, it seems, because there's an *account-level* setting for "Notifications" which I had turned off, which apparently is interpreted as meaning "I don't want room highlights". By both Element and Quaternion. That seems surprising, but hey. It's the setting Element shows as "Enable notifications for this account" in notification settings; if that's off, I get no room highlights in either Element or Quaternion. If it's on, I get room highlights in both.

The *message* highlight bug does indeed seem to be due to the two-of-me problem. In channels where there's only one of me, I get message highlights. In channels where there are two `adamw`s, I don't, apparently because Quaternion is deciding the message is to the other one.

**Comment by AdamWill** [comment] 2020-12-01 19:08
So this might be a Matrix-level issue rather than an Element one, I guess? I don't know Matrix well enough to know *exactly* what Quaternion as a client is getting here. Perhaps something further up the chain already decided the tag was "for" the "other adamw" and that information is already in the message as Quaternion sees it?

**Comment by KitsuneRal** [comment] 2021-03-06 10:31
Sorry for a long silence. TL;DR: you seem to be right in your conclusions; the underlying problem for the second issue is that you have split identities between Matrix and IRC, and connecting them together (see below) might be a good idea. There's nothing wrong with Quaternion to that end though so I'm going to close this issue.

On the first issue, you figured it right: highlights in Element are configured account-wise, not client-wise. This may be surprising for users coming from IRC and other networks that don't maintain account data across clients. That said, if you turn notifications on in Element (actually - on the homeserver) you can still turn them off in Quaternion because Quaternion configures them locally (but if they are off on the homeserver, Quaternion receives nothing no matter its own configuration).

On the second issue, if a particular message is aimed at `@freenode_adamw:matrix.org` then it won't be highlighted for you-as-Matrix-user. The most reliable way to check the mentioned user id is to look at the message's JSON - find a message where you're mentioned and choose "Source code" (Element) or "Show details" (Quaternion) in the context menu. I'm not quite sure if people in IRC even see your Matrix identity (and even if they do, it surely doesn't look like plain `adamw`, which is why they mention your IRC account).

I'm not very knowledgeable in bridges but if you'd like to use your IRC identity from your Matrix account - invite `@freenode-irc:matrix.org`, type `!help` and you should be able to figure out your way from there (`!nick` is one of the first things you'll likely want to do). For integration in the opposite direction, `@freenode_adamw:matrix.org` is a synthetic user in order to make Matrix rooms accessible to IRC users; but if you're using Matrix, you shouldn't need that user. You may want to ask in [#irc:matrix.org](https://matrix.to/#/#irc:matrix.org) what to do with this user in rooms where it exists.

**Closed** 2021-03-06 10:31 UTC
Labels: invalid
