### ISSUE TITLE
[Feature Request] Add search in main window 

### ISSUE THREAD

**Issue by pretentious7** [quotient-im/Quaternion#669] opened 2020-04-05 03:19 UTC
### Description

I'd like to see a search feature for the chat, as this doesn't seem to exist right now and would be useful. 

### Version information

- **Quaternion version**: 0.0.9.4
- **Qt version**: 
- **Install method**: Flatpak
- **Platform**: Ubuntu 18.04

**Comment by aaronraimist** [comment] 2020-04-05 05:06
Duplicate of https://github.com/quotient-im/Quaternion/issues/258, please thumbs up that issue

**Closed by aaronraimist** 2020-04-05 05:06 UTC
